const images = {
  a: require("./alphabet_signs/a.png"),
  b: require("./alphabet_signs/b.png"),
  c: require("./alphabet_signs/c.png"),
  d: require("./alphabet_signs/d.png"),
  e: require("./alphabet_signs/e.png"),
  f: require("./alphabet_signs/f.png"),
  g: require("./alphabet_signs/g.png"),
  h: require("./alphabet_signs/h.png"),
  i: require("./alphabet_signs/i.png"),
  j: require("./alphabet_signs/j.png"),
  k: require("./alphabet_signs/k.png"),
  l: require("./alphabet_signs/l.png"),
  m: require("./alphabet_signs/m.png"),
  n: require("./alphabet_signs/n.png"),
  o: require("./alphabet_signs/o.png"),
  p: require("./alphabet_signs/p.png"),
  q: require("./alphabet_signs/q.png"),
  r: require("./alphabet_signs/r.png"),
  s: require("./alphabet_signs/s.png"),
  t: require("./alphabet_signs/t.png"),
  u: require("./alphabet_signs/u.png"),
  v: require("./alphabet_signs/v.png"),
  w: require("./alphabet_signs/w.png"),
  x: require("./alphabet_signs/x.png"),
  y: require("./alphabet_signs/y.png"),
  z: require("./alphabet_signs/z.png"),
}
export default images;